### ISSUE TITLE
Dependencies are not listed

### ISSUE THREAD

**Issue by trickeydan** [PeterJCLaw/srcomp-dev#3]
I have just tried to use this to get a working version of `srcomp` working.

Please could you list the dependencies that are required for `init.sh` to work, e.g `npm`, `bower` etc 

I have also encountered an issue with `invalid command bdist_wheel` which I think is to do with python versions.

**Comment by PeterJCLaw** [comment]
The dependencies are checked for by the `init.sh`, with errors reported if they are missing. I'd rather not duplicate them beyond that, especially as the script is already duplicating them out of the individual repos which it is setting up.

I suspect the lack of `bdist_wheel` on your system is a result of using an old version of `setuptools` -- can you run `pip list` in your environment?

**Comment by trickeydan** [comment]
`setuptools (36.2.7)`

Also of note, the `init.sh` script currently defaults to Python 2, rather than Python 3.

**Comment by PeterJCLaw** [comment]
That setuptools looks fairly recent. @prophile what does `bdist_wheel` rely on? Is there a reason that @trickeydan wouldn't have it?

SRComp supports Python 2 and 3, though it has been used on Python 2 much more. I don't think there's immediate cause to change the default.

Note that this repo is intended for _developers_ who want to understand SRComp. As a result I see the `init.sh` as being documentation as much as code, and very much as something which the user will likely be able to poke around as needed.
I don't see this repo as a way to set up a black-box SRComp for building on top of. For that, I would recommend using https://github.com/PeterJCLaw/srcomp-puppet to configure a compbox.
