### ISSUE TITLE
Python is incorrectly detected on Arch Linux

### ISSUE THREAD

**Issue by trickeydan** [PeterJCLaw/srcomp-dev#5]
```
╭─dan@dgt-laptop ~/Code/srcomp-dev ‹master›
╰─$ ./init.sh                                                                            243 ↵
Found Python: /usr/bin/python2
1.8.8
/usr/bin/python2: No module named venv
```

`venv` is a python3 module.

I suspect this is due to the non-standard python setup that Arch systems use, but it is worth noting and putting in a fix for. There are a reasonable number of volunteers who use this distro.

**Comment by PeterJCLaw** [comment]
It's also possible that this is just wrongly configured -- it probably shouldn't be trying to use `venv` with Python 2, as you said.

This may be moot however as I plan to drop Python 2 support soon:tm: anyway.

**Comment by PeterJCLaw** [comment]
We've now done the aforementioned move to Python 3 only, would be good to know if that solves this.

**Comment by trickeydan** [comment]
This appears to be resolved now :)
